logo_title: geek & gamer

style: black

favicon: /favicon.ico

menu:
  Archives: /archives
  About: /about
  Github: https://github.com/iiiypuk

# 做了域名限制，请改成自己的 KEY
# 若关闭valine 设置enable为false
valine:
  enable: false
  appId:
  appKey:

highlight:
  enable: true