logo_title: geek & gamer
author: iiiypuk # use in footer

style: black

favicon: /favicon.ico

menu:
  Archives: /archives
  About: /about
  Github: https://github.com/iiiypuk
  Twitter: https://twitter.com/@iiiypuk
  Vk: https://vk.com/0xi3k

highlight:
  enable: true
